// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH_Fy5CGS3HFTYSO31t3KNfrKxffDJlXo',
    appId: '1:469509834193:web:9ce2bdb856d2b163a5ccf0',
    messagingSenderId: '469509834193',
    projectId: 'gardening-flutter',
    authDomain: 'gardening-flutter.firebaseapp.com',
    storageBucket: 'gardening-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbNGAynF0_QNP6jRx7dDjY988DADgp9NQ',
    appId: '1:469509834193:android:890f38b206fe58e1a5ccf0',
    messagingSenderId: '469509834193',
    projectId: 'gardening-flutter',
    storageBucket: 'gardening-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpl4sztaQ66PJaWaO5xtnyM82609ti6tw',
    appId: '1:469509834193:ios:4d2954e022fb79cfa5ccf0',
    messagingSenderId: '469509834193',
    projectId: 'gardening-flutter',
    storageBucket: 'gardening-flutter.appspot.com',
    iosClientId: '469509834193-1kerkverfil3tc1pl1p6b3do5qcf7eui.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardenTa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpl4sztaQ66PJaWaO5xtnyM82609ti6tw',
    appId: '1:469509834193:ios:b40d612b0c14df0aa5ccf0',
    messagingSenderId: '469509834193',
    projectId: 'gardening-flutter',
    storageBucket: 'gardening-flutter.appspot.com',
    iosClientId: '469509834193-9cta5biorff32u8q3oq79f74hurj636r.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardenTa.RunnerTests',
  );
}
